The thrown Exception: Invalid Item-ID for ID: 5

se.kth.iv1350.sempos.model.InvalidIdentifierOfItemException: Invalid Item-ID for ID: 5

	at se.kth.iv1350.sempos.Integration.InventorySystem.getItemInformation(InventorySystem.java:37)
	at se.kth.iv1350.sempos.controller.Controller.registerItem(Controller.java:48)
	at se.kth.iv1350.sempos.view.View.scanItem(View.java:62)
	at se.kth.iv1350.sempos.view.View.runFakeExecution(View.java:36)
	at se.kth.iv1350.sempos.startup.Main.main(Main.java:27)


The thrown Exception: Error can not connect to server. Item-ID 4 does not exists.
se.kth.iv1350.sempos.Integration.DatabaseFailureException: Error can not connect to server. Item-ID 4 does not exists.
	at se.kth.iv1350.sempos.Integration.InventorySystem.getItemInformation(InventorySystem.java:34)
	at se.kth.iv1350.sempos.controller.Controller.registerItem(Controller.java:48)
	at se.kth.iv1350.sempos.view.View.scanItem(View.java:62)
	at se.kth.iv1350.sempos.view.View.runFakeExecution(View.java:38)
	at se.kth.iv1350.sempos.startup.Main.main(Main.java:27)


